function makeRouteDraft(day=today()){
  const selectedDogs=dogs.filter(d=>d.walking&&postcodeOf(d));const selected={};selectedDogs.slice(0,Math.min(3,selectedDogs.length)).forEach(d=>selected[d.id]=pickupForDay(d,day));
  return {day,destinationId:settings.destinations[0]?.id||'',arrival:'10:00',stopMinutes:5,tolerance:10,trafficBuffer:10,selected,result:null};
}
function route(){
  pageTitle.textContent='Pickup Route';if(!routeDraft)routeDraft=makeRouteDraft();const dayDogs=dogs.filter(d=>d.walking),destinations=settings.destinations||[];
  app.innerHTML=`<button class="text-button" data-back>‹ Back</button><div class="route-box"><div class="section-title-row"><h2>Walking route planner</h2></div><p>Choose the dogs to collect, the field Jess needs to reach, and the time she needs to be there. The planner works backwards and tests different collection orders.</p><div class="meta-grid two"><label><span>Walking day</span><select id="route-day">${DAYS.map(d=>`<option ${d===routeDraft.day?'selected':''}>${d}</option>`).join('')}</select></label><label><span>Destination field</span><select id="route-destination"><option value="">Choose field</option>${destinations.map(d=>`<option value="${d.id}" ${d.id===routeDraft.destinationId?'selected':''}>${esc(d.name)}</option>`).join('')}</select></label></div><div class="meta-grid two"><label><span>Need to arrive by</span><input id="field-arrival" type="time" value="${esc(routeDraft.arrival)}"></label><label><span>Minutes spent at each house</span><input id="stop-minutes" type="number" min="0" max="30" step="1" value="${routeDraft.stopMinutes}"></label></div><div class="meta-grid two"><label><span>Allowed pickup lateness (mins)</span><input id="pickup-tolerance" type="number" min="0" max="60" step="1" value="${routeDraft.tolerance}"></label><label><span>Traffic / parking buffer (mins)</span><input id="traffic-buffer" type="number" min="0" max="60" step="1" value="${routeDraft.trafficBuffer}"></label></div><div class="section" style="margin-top:16px"><div class="section-title-row"><h3>Dogs to collect</h3></div><div class="route-picker">${dayDogs.length?dayDogs.map(d=>{const pc=postcodeOf(d),checked=Object.prototype.hasOwnProperty.call(routeDraft.selected,d.id),t=routeDraft.selected[d.id]??pickupForDay(d,routeDraft.day);return `<label class="route-option"><input class="route-dog-check" type="checkbox" value="${d.id}" ${checked?'checked':''} ${pc?'':'disabled'}><span><strong>${esc(d.name)}</strong><small style="display:block;color:var(--muted);margin-top:2px">${pc?esc(fullAddress(d)):'Add a postcode to use in route planning'}</small></span><input class="pickup-time" data-pickup-id="${d.id}" type="time" value="${esc(t||'')}" ${pc?'':'disabled'} aria-label="${esc(d.name)} pickup time"></label>`}).join(''):'<p class="muted">No walking dogs have been added yet.</p>'}</div></div><div class="planner-actions">${destinations.length?'<button id="calculate-route" class="primary-button" type="button">Calculate best route</button>':'<button class="primary-button" data-add-location type="button">Add a destination field</button>'}</div><p class="route-warning">Route calculations are estimates and do not include live traffic. Only postcodes are used to obtain coordinates; full client addresses are sent to Google Maps only when Jess chooses to open the finished route.</p><div id="route-result">${routeDraft.result?routeResultHtml(routeDraft.result):''}</div></div>`;
  $('#fab').hidden=true;bindRouteControls();
}
function bindRouteControls(){
  $('#route-day')?.addEventListener('change',e=>{routeDraft=makeRouteDraft(e.target.value);route()});
  $('#route-destination')?.addEventListener('change',e=>{routeDraft.destinationId=e.target.value;routeDraft.result=null});
  $('#field-arrival')?.addEventListener('change',e=>{routeDraft.arrival=e.target.value;routeDraft.result=null});
  $('#stop-minutes')?.addEventListener('change',e=>{routeDraft.stopMinutes=clampNumber(e.target.value,0,30,5);routeDraft.result=null});
  $('#pickup-tolerance')?.addEventListener('change',e=>{routeDraft.tolerance=clampNumber(e.target.value,0,60,10);routeDraft.result=null});
  $('#traffic-buffer')?.addEventListener('change',e=>{routeDraft.trafficBuffer=clampNumber(e.target.value,0,60,10);routeDraft.result=null});
  app.querySelectorAll('.route-dog-check').forEach(ch=>ch.onchange=()=>{const t=app.querySelector(`[data-pickup-id="${CSS.escape(ch.value)}"]`)?.value||'';if(ch.checked)routeDraft.selected[ch.value]=t;else delete routeDraft.selected[ch.value];routeDraft.result=null});
  app.querySelectorAll('[data-pickup-id]').forEach(inp=>inp.onchange=()=>{const id=inp.dataset.pickupId;if(app.querySelector(`.route-dog-check[value="${CSS.escape(id)}"]`)?.checked)routeDraft.selected[id]=inp.value;routeDraft.result=null});
  $('#calculate-route')?.addEventListener('click',calculateRoute);$('#open-optimized-route')?.addEventListener('click',openOptimizedRoute);
}
async function postcodeCoord(postcode){const pc=cleanPostcode(postcode);if(!pc)throw new Error('Missing postcode');if(postcodeCache[pc])return postcodeCache[pc];const res=await fetch(`https://api.postcodes.io/postcodes/${encodeURIComponent(pc)}`,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error(`Postcode ${pc} was not found`);const data=await res.json(),lat=data?.result?.latitude,lon=data?.result?.longitude;if(!Number.isFinite(lat)||!Number.isFinite(lon))throw new Error(`Postcode ${pc} has no coordinates`);postcodeCache[pc]={lat,lon};await savePostcodeCache();return postcodeCache[pc]}
async function roadMatrix(points){
  const coords=points.map(p=>`${p.lon},${p.lat}`).join(';');
  try{const res=await fetch(`https://router.project-osrm.org/table/v1/driving/${coords}?annotations=duration,distance`);if(!res.ok)throw new Error('Road service unavailable');const x=await res.json();if(x.code!=='Ok'||!Array.isArray(x.durations))throw new Error('Road service unavailable');return {durations:x.durations.map(r=>r.map(v=>v==null?Infinity:v/60)),distances:(x.distances||[]).map(r=>r.map(v=>v==null?Infinity:v/1000)),fallback:false}}
  catch{const n=points.length,durations=Array.from({length:n},()=>Array(n).fill(0)),distances=Array.from({length:n},()=>Array(n).fill(0));for(let i=0;i<n;i++)for(let j=0;j<n;j++){const km=haversine(points[i],points[j]);distances[i][j]=km;durations[i][j]=i===j?0:(km/42*60)+2}return {durations,distances,fallback:true}}
}
function haversine(a,b){const R=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lon-a.lon),la1=toRad(a.lat),la2=toRad(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
function permutations(items){const out=[];function walk(prefix,rest){if(!rest.length){out.push(prefix);return}for(let i=0;i<rest.length;i++)walk([...prefix,rest[i]],[...rest.slice(0,i),...rest.slice(i+1)])}walk([],items);return out}
function simulate(order,depart,matrix,targets,stopMinutes,tolerance,deadline){let t=depart,prev=0,drive=0,wait=0;const stops=[];for(const dogIndex of order){const pointIndex=dogIndex+1,leg=matrix.durations[prev][pointIndex];if(!Number.isFinite(leg))return {feasible:false};t+=leg;drive+=leg;const arrival=t,target=targets[dogIndex];if(target!=null&&t<target){wait+=target-t;t=target}const pickup=t,late=target==null?0:pickup-target;if(target!=null&&late>tolerance+.01)return {feasible:false};stops.push({dogIndex,arrival,pickup,target,leg,late});t+=stopMinutes;prev=pointIndex}const destIndex=matrix.durations.length-1,finalLeg=matrix.durations[prev][destIndex];if(!Number.isFinite(finalLeg))return {feasible:false};t+=finalLeg;drive+=finalLeg;return {feasible:t<=deadline+.01,depart,stops,fieldArrival:t,finalLeg,drive,wait}}
function latestFeasible(order,matrix,targets,stopMinutes,tolerance,deadline){const earliest=simulate(order,0,matrix,targets,stopMinutes,tolerance,deadline);if(!earliest.feasible)return null;let lo=0,hi=deadline;for(let i=0;i<28;i++){const mid=(lo+hi)/2,s=simulate(order,mid,matrix,targets,stopMinutes,tolerance,deadline);if(s.feasible)lo=mid;else hi=mid}return simulate(order,lo,matrix,targets,stopMinutes,tolerance,deadline)}
function totalDistance(order,matrix){let prev=0,total=0;for(const d of order){total+=matrix.distances[prev][d+1]||0;prev=d+1}total+=matrix.distances[prev][matrix.distances.length-1]||0;return total}
function optimize(orderDogs,matrix,pickups,stopMinutes,tolerance,deadline){const targets=orderDogs.map(d=>timeToMin(pickups[d.id])),indexes=orderDogs.map((_,i)=>i),perms=permutations(indexes);let best=null;for(const order of perms){const sim=latestFeasible(order,matrix,targets,stopMinutes,tolerance,deadline);if(!sim)continue;const distance=totalDistance(order,matrix);if(!best||sim.drive<best.sim.drive-.1||(Math.abs(sim.drive-best.sim.drive)<.1&&distance<best.distance-.05)||(Math.abs(sim.drive-best.sim.drive)<.1&&Math.abs(distance-best.distance)<.05&&sim.depart>best.sim.depart))best={order,sim,distance}}return best}
async function calculateRoute(){
  syncRouteDraftFromForm();const resultBox=$('#route-result'),button=$('#calculate-route'),selectedIds=Object.keys(routeDraft.selected);
  if(!settings.start||!postcodeOf(settings.start))return showRouteError('Set Jess’s starting location and postcode on the Home page first.');const destination=settings.destinations.find(l=>l.id===routeDraft.destinationId);if(!destination||!postcodeOf(destination))return showRouteError('Choose a destination field with a postcode.');if(!selectedIds.length)return showRouteError('Select at least one dog to collect.');if(selectedIds.length>7)return showRouteError('Select up to 7 dogs at a time so the route can be optimised reliably on the phone.');const selectedDogs=selectedIds.map(id=>dogs.find(d=>d.id===id)).filter(Boolean);if(selectedDogs.some(d=>!postcodeOf(d)))return showRouteError('Every selected dog needs a postcode.');const arrival=timeToMin(routeDraft.arrival);if(arrival==null)return showRouteError('Add the time Jess needs to reach the field.');const deadline=arrival-routeDraft.trafficBuffer;if(deadline<=0)return showRouteError('The traffic buffer is larger than the available day.');button.disabled=true;button.textContent='Calculating…';resultBox.innerHTML='<div class="planner-status">Checking postcodes and road travel times…</div>';
  try{const pointRecords=[settings.start,...selectedDogs,destination],points=[];for(const p of pointRecords)points.push(await postcodeCoord(postcodeOf(p)));const matrix=await roadMatrix(points),best=optimize(selectedDogs,matrix,routeDraft.selected,routeDraft.stopMinutes,routeDraft.tolerance,deadline);if(!best){routeDraft.result=null;resultBox.innerHTML='<div class="planner-status error">No collection order can meet all of those pickup times and still reach the field on time. Try increasing the allowed pickup lateness, reducing time at each house, or changing one of the pickup times.</div>';return}const orderedDogs=best.order.map(i=>selectedDogs[i]),stops=best.sim.stops.map(s=>({...s,dog:selectedDogs[s.dogIndex]}));routeDraft.result={orderedDogs,stops,depart:best.sim.depart,fieldArrival:best.sim.fieldArrival,finalLeg:best.sim.finalLeg,drive:best.sim.drive,distance:best.distance,destination,arrivalTarget:arrival,buffer:routeDraft.trafficBuffer,fallback:matrix.fallback,day:routeDraft.day};resultBox.innerHTML=routeResultHtml(routeDraft.result);$('#open-optimized-route')?.addEventListener('click',openOptimizedRoute)}catch(err){showRouteError(err?.message||'The route could not be calculated. Check the postcodes and internet connection.')}finally{button.disabled=false;button.textContent='Calculate best route'}
}
function syncRouteDraftFromForm(){routeDraft.arrival=$('#field-arrival')?.value||routeDraft.arrival;routeDraft.destinationId=$('#route-destination')?.value||routeDraft.destinationId;routeDraft.stopMinutes=clampNumber($('#stop-minutes')?.value,0,30,5);routeDraft.tolerance=clampNumber($('#pickup-tolerance')?.value,0,60,10);routeDraft.trafficBuffer=clampNumber($('#traffic-buffer')?.value,0,60,10);const selected={};app.querySelectorAll('.route-dog-check:checked').forEach(ch=>{selected[ch.value]=app.querySelector(`[data-pickup-id="${CSS.escape(ch.value)}"]`)?.value||''});routeDraft.selected=selected}
function showRouteError(message){const box=$('#route-result');if(box)box.innerHTML=`<div class="planner-status error">${esc(message)}</div>`}
function routeResultHtml(r){const plannedField=minToTime(r.fieldArrival),target=minToTime(r.arrivalTarget);let prevName='Start';const rows=r.stops.map(s=>{const scheduled=s.target==null?'No fixed pickup time':`Scheduled ${minToTime(s.target)}`,drive=Math.max(1,Math.round(s.leg)),html=`<div class="timeline-row"><div class="timeline-time">${minToTime(s.pickup)}</div><div class="timeline-mark"></div><div class="timeline-copy"><strong>Collect ${esc(s.dog.name)}</strong><small>${drive} min drive from ${esc(prevName)} · ${scheduled}</small></div></div>`;prevName=s.dog.name;return html}).join('');return `<section class="route-result"><div class="leave-card"><small>LEAVE BY</small><strong>${minToTime(r.depart)}</strong><p>${r.day} · about ${Math.round(r.drive)} min driving · ${r.distance.toFixed(1)} km</p></div><div class="timeline"><div class="timeline-row"><div class="timeline-time">${minToTime(r.depart)}</div><div class="timeline-mark"></div><div class="timeline-copy"><strong>Leave starting location</strong><small>${esc(fullAddress(settings.start))}</small></div></div>${rows}<div class="timeline-row"><div class="timeline-time">${plannedField}</div><div class="timeline-mark"></div><div class="timeline-copy"><strong>Arrive at ${esc(r.destination.name)}</strong><small>${Math.max(1,Math.round(r.finalLeg))} min drive from ${esc(prevName)}${r.buffer?` · ${r.buffer} min before ${target} target`:''}</small></div></div></div>${r.fallback?'<div class="route-warning">The road-routing service was unavailable, so this result uses a rough straight-line driving estimate. Recalculate before relying on the times.</div>':'<div class="route-warning">Times are road estimates, not live traffic. The extra buffer is included in the leave-by time. Road data © OpenStreetMap contributors.</div>'}<button id="open-optimized-route" class="primary-button" type="button" style="width:100%;margin-top:12px">Open this order in Google Maps</button></section>`}
function openOptimizedRoute(){const r=routeDraft?.result;if(!r)return;if(r.orderedDogs.length>3)toast('Google Maps on some mobile browsers may limit routes to 3 intermediate stops');const origin=fullAddress(settings.start),destination=fullAddress(r.destination),waypoints=r.orderedDogs.map(fullAddress).filter(Boolean).join('|'),url=`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}${waypoints?`&waypoints=${encodeURIComponent(waypoints)}`:''}&travelmode=driving`;open(url,'_blank','noopener')}
