(()=>{
const KEY='jda-dogs-v1',DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const $=s=>document.querySelector(s), app=$('#app'), pageTitle=$('#page-title'), dogDlg=$('#dog-dialog'), detailDlg=$('#detail-dialog'), dataDlg=$('#data-dialog');
const walkSlots=$('#walk-slots'),sitSlots=$('#sit-slots'),walkOn=$('#walking-enabled'),sitOn=$('#sitting-enabled'),walkEditor=$('#walking-editor'),sitEditor=$('#sitting-editor');
let dogs=load(),view='home';
function load(){try{let x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(dogs))}
function esc(v=''){return String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function avatar(d){return d.photo?`<img class="dog-avatar" src="${d.photo}" alt="${esc(d.name)}">`:`<div class="avatar-fallback">${esc((d.name||'?')[0].toUpperCase())}</div>`}
function today(){return new Intl.DateTimeFormat('en-GB',{weekday:'long'}).format(new Date())}
function dateLabel(){return new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}
function jobs(type,day=today()){return dogs.flatMap(d=>{let on=type==='walk'?d.walking:d.sitting,s=type==='walk'?d.walkSchedule:d.sitSchedule;return on?(s||[]).filter(x=>x.day===day).map(slot=>({d,slot,type})):[]}).sort((a,b)=>(a.slot.time||'99:99').localeCompare(b.slot.time||'99:99'))}
function tags(d){return`${d.walking?'<span class="tag">Walking</span>':''}${d.sitting?'<span class="tag sit">Sitting</span>':''}${d.hasKey?'<span class="tag key">Key held</span>':''}`}
function dogCard(d){return`<button class="dog-card" data-dog="${d.id}">${avatar(d)}<span class="card-main"><strong>${esc(d.name)}</strong><small>${esc([d.breed,d.owner&&`Owner: ${d.owner}`].filter(Boolean).join(' · ')||'No extra details yet')}</small><span class="tag-row">${tags(d)}</span></span><span class="card-chevron">›</span></button>`}
function jobCard(x){return`<button class="job-card" data-dog="${x.d.id}">${avatar(x.d)}<span class="card-main"><strong>${esc(x.d.name)}</strong><small>${x.type==='walk'?'Walk':'Sitting'}${x.d.address?' · '+esc(x.d.address.split('\n')[0]):''}</small></span><strong>${esc(x.slot.time||'Any time')}</strong></button>`}
function empty(h,p,b='Add a dog'){return`<div class="empty-state"><div class="empty-icon">●</div><h3>${esc(h)}</h3><p>${esc(p)}</p><button class="primary-button" data-add>${esc(b)}</button></div>`}
function home(){pageTitle.textContent='Today';let w=jobs('walk'),s=jobs('sit'),all=[...w,...s].sort((a,b)=>(a.slot.time||'99:99').localeCompare(b.slot.time||'99:99'));app.innerHTML=`<section class="hero"><p class="date">${esc(dateLabel())}</p><div class="hero-count"><strong>${all.length}</strong><span>${all.length===1?'job today':'jobs today'}</span></div><p class="hero-sub">${dogs.length?`${dogs.length} ${dogs.length===1?'dog':'dogs'} saved`:'Add your first dog to get started'}</p></section><section class="quick-grid"><button class="quick-card" data-go="dogs"><span class="quick-symbol">●</span><strong>${dogs.length}</strong><small>All dogs</small></button><button class="quick-card" data-go="walks"><span class="quick-symbol">↗</span><strong>${w.length}</strong><small>Walks today</small></button><button class="quick-card" data-go="sitting"><span class="quick-symbol">⌂</span><strong>${s.length}</strong><small>Sitting today</small></button><button class="quick-card" data-route><span class="quick-symbol">⌖</span><strong>${dogs.filter(d=>d.address).length}</strong><small>Route-ready</small></button></section><section class="section"><div class="section-title-row"><h2>Today's schedule</h2></div><div class="list">${all.length?all.map(jobCard).join(''):empty('Nothing scheduled today',dogs.length?'There are no walks or sitting times saved for today.':'Add a dog and its schedule to see today’s jobs here.')}</div></section>`}
function allDogs(q=''){pageTitle.textContent='All Dogs';let f=dogs.filter(d=>[d.name,d.breed,d.owner,d.address].some(v=>(v||'').toLowerCase().includes(q.toLowerCase())));app.innerHTML=`<div class="search-wrap"><input id="dog-search" type="search" placeholder="Search dogs, owners or addresses" value="${esc(q)}"></div><div class="list">${f.length?f.map(dogCard).join(''):dogs.length?empty('No matches','Try a different search.','Clear search'):empty('No dogs yet','Add Jess’s first dog profile.')}</div>`;$('#dog-search').oninput=e=>allDogs(e.target.value);if(dogs.length&&!f.length)$('[data-add]').onclick=()=>allDogs('')}
function schedule(type){let isWalk=type==='walk',active=dogs.filter(d=>isWalk?d.walking:d.sitting),slots=active.flatMap(d=>(isWalk?d.walkSchedule:d.sitSchedule||[]).map(slot=>({d,slot}))),groups=DAYS.map(day=>({day,list:slots.filter(x=>x.slot.day===day).sort((a,b)=>(a.slot.time||'99:99').localeCompare(b.slot.time||'99:99'))})).filter(g=>g.list.length);pageTitle.textContent=isWalk?'Walking':'Sitting';app.innerHTML=`${active.length?`<section class="section" style="margin-top:0"><div class="section-title-row"><h2>${active.length} ${active.length===1?'dog':'dogs'}</h2><span class="muted">Weekly schedule</span></div></section>`:''}${groups.length?groups.map(g=>`<section class="schedule-day"><h3>${g.day}</h3><div class="list">${g.list.map(x=>`<button class="schedule-card" data-dog="${x.d.id}"><span class="schedule-time">${esc(x.slot.time||'—')}</span>${avatar(x.d)}<span class="card-main"><strong>${esc(x.d.name)}</strong><small>${esc(x.d.address?x.d.address.split('\n')[0]:x.d.breed||'')}</small></span><span class="card-chevron">›</span></button>`).join('')}</div></section>`).join(''):empty(isWalk?'No walking schedule yet':'No sitting schedule yet',isWalk?'Turn on Walking in a dog profile and add the days and times.':'Turn on Sitting in a dog profile and add the days and times.')}${isWalk&&active.some(d=>d.address)?'<section class="section"><button class="secondary-button" style="width:100%" data-route>Plan a pickup route</button></section>':''}`}
function route(){view='route';pageTitle.textContent='Pickup Route';let list=dogs.filter(d=>d.walking&&d.address);app.innerHTML=`<button class="text-button" data-back>‹ Back</button><div class="route-box"><h2>Walking pickup route</h2><p>Select the dogs you want to collect. Their saved addresses will open together in Google Maps as a driving route.</p>${list.length?`<div class="route-picker">${list.map((d,i)=>`<label class="route-option"><input type="checkbox" value="${d.id}" ${i<8?'checked':''}><span><strong>${esc(d.name)}</strong><small style="display:block;color:var(--muted);margin-top:2px">${esc(d.address.replace(/\n/g,', '))}</small></span></label>`).join('')}</div><button id="open-route" class="primary-button" style="width:100%">Open route in Google Maps</button>`:empty('No route-ready dogs','A dog needs Walking turned on and a saved address before it can be added to a pickup route.')}</div>`;$('#fab').hidden=true}
function setView(v){view=v;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#fab').hidden=false;if(v==='home')home();if(v==='dogs')allDogs();if(v==='walks')schedule('walk');if(v==='sitting')schedule('sit');if(v==='route')route();scrollTo(0,0)}
function addSlot(box,x={day:'Monday',time:''}){let r=$('#schedule-row-template').content.firstElementChild.cloneNode(true);r.querySelector('.slot-day').value=x.day||'Monday';r.querySelector('.slot-time').value=x.time||'';r.querySelector('.remove-slot').onclick=()=>r.remove();box.append(r)}
function readSlots(box){return[...box.querySelectorAll('.schedule-row')].map(r=>({day:r.querySelector('.slot-day').value,time:r.querySelector('.slot-time').value}))}
function photo(src=''){let img=$('#photo-preview'),ph=$('#photo-placeholder');$('#photo-data').value=src;if(src){img.src=src;img.hidden=false;ph.hidden=true}else{img.hidden=true;ph.hidden=false;img.removeAttribute('src')}}
function editDog(d=null){$('#dog-form').reset();walkSlots.innerHTML=sitSlots.innerHTML='';$('#dog-id').value=d?.id||'';$('#dog-form-title').textContent=d?'Edit dog':'Add dog';$('#delete-dog').hidden=!d;['name','breed','age','owner','address','special','other'].forEach(k=>$(`#${k}`).value=d?.[k]||'');document.querySelector(`input[name="has-key"][value="${d?.hasKey?'yes':'no'}"]`).checked=true;walkOn.checked=!!d?.walking;sitOn.checked=!!d?.sitting;walkEditor.hidden=!walkOn.checked;sitEditor.hidden=!sitOn.checked;(d?.walkSchedule||[]).forEach(x=>addSlot(walkSlots,x));(d?.sitSchedule||[]).forEach(x=>addSlot(sitSlots,x));if(walkOn.checked&&!walkSlots.children.length)addSlot(walkSlots);if(sitOn.checked&&!sitSlots.children.length)addSlot(sitSlots);photo(d?.photo||'');dogDlg.showModal()}
function saveDog(){let name=$('#name').value.trim();if(!name){$('#name').focus();return toast('Please add the dog’s name')}let id=$('#dog-id').value||(crypto.randomUUID?crypto.randomUUID():Date.now()+''),d={id,photo:$('#photo-data').value,name,breed:$('#breed').value.trim(),age:$('#age').value.trim(),owner:$('#owner').value.trim(),address:$('#address').value.trim(),hasKey:$('input[name="has-key"]:checked').value==='yes',special:$('#special').value.trim(),other:$('#other').value.trim(),walking:walkOn.checked,walkSchedule:walkOn.checked?readSlots(walkSlots):[],sitting:sitOn.checked,sitSchedule:sitOn.checked?readSlots(sitSlots):[]},i=dogs.findIndex(x=>x.id===id);i<0?dogs.push(d):dogs[i]=d;save();dogDlg.close();setView(view==='route'?'home':view);toast(i<0?'Dog added':'Dog updated')}
function detail(id){let d=dogs.find(x=>x.id===id);if(!d)return;let fmt=s=>s?.length?s.map(x=>`${x.day} · ${x.time||'Any time'}`).join('\n'):'No times saved';detailDlg.innerHTML=`<div class="sheet-head"><p class="eyebrow">DOG PROFILE</p><button class="close-button" data-close-detail>×</button></div><div class="detail-hero">${avatar(d)}<h2>${esc(d.name)}</h2><p>${esc([d.breed,d.age].filter(Boolean).join(' · ')||'Dog profile')}</p><div class="tag-row" style="justify-content:center">${tags(d)}</div></div><div class="detail-grid"><div class="info-box"><small>Owner</small><p>${esc(d.owner||'—')}</p></div><div class="info-box"><small>Key to premises</small><p>${d.hasKey?'Yes':'No'}</p></div><div class="info-box wide"><small>Address</small><p>${esc(d.address||'—')}</p></div>${d.walking?`<div class="info-box wide"><small>Walk schedule</small><p>${esc(fmt(d.walkSchedule))}</p></div>`:''}${d.sitting?`<div class="info-box wide"><small>Sitting schedule</small><p>${esc(fmt(d.sitSchedule))}</p></div>`:''}<div class="info-box wide"><small>Special requirements</small><p>${esc(d.special||'—')}</p></div><div class="info-box wide"><small>Other info</small><p>${esc(d.other||'—')}</p></div></div><div class="detail-actions">${d.address?'<button class="secondary-button" data-map>Open address</button>':''}<button class="primary-button ${d.address?'':'full'}" data-edit>Edit dog</button></div>`;detailDlg.querySelector('[data-close-detail]').onclick=()=>detailDlg.close();detailDlg.querySelector('[data-edit]').onclick=()=>{detailDlg.close();editDog(d)};detailDlg.querySelector('[data-map]')?.addEventListener('click',()=>map(d.address));detailDlg.showModal()}
function map(a){open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(a)}`,'_blank','noopener')}
function openRoute(){let sel=[...app.querySelectorAll('.route-option input:checked')].map(x=>dogs.find(d=>d.id===x.value)).filter(Boolean);if(!sel.length)return toast('Select at least one dog');if(sel.length===1)return map(sel[0].address);let a=sel.map(d=>d.address.replace(/\n/g,', ')),o=a[0],dest=a.at(-1),way=a.slice(1,-1).join('|');open(`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(o)}&destination=${encodeURIComponent(dest)}${way?`&waypoints=${encodeURIComponent(way)}`:''}&travelmode=driving`,'_blank','noopener')}
function shrink(file){return new Promise((res,rej)=>{let r=new FileReader;r.onerror=rej;r.onload=()=>{let im=new Image;im.onerror=rej;im.onload=()=>{let max=800,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*s;c.height=im.height*s;c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.8))};im.src=r.result};r.readAsDataURL(file)})}
function backup(){let b=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),dogs},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`jess-dog-organiser-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup exported')}
async function restore(file){if(!file)return;try{let x=JSON.parse(await file.text()),list=Array.isArray(x)?x:x.dogs;if(!Array.isArray(list))throw 0;if(!confirm(`Restore ${list.length} dog profile${list.length===1?'':'s'}? This replaces the data on this device.`))return;dogs=list;save();dataDlg.close();setView(view);toast('Backup restored')}catch{toast('That backup file could not be read')}}
function del(){let id=$('#dog-id').value,d=dogs.find(x=>x.id===id);if(!d||!confirm(`Delete ${d.name}? This cannot be undone.`))return;dogs=dogs.filter(x=>x.id!==id);save();dogDlg.close();setView(view);toast('Dog deleted')}
function toast(m){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
document.addEventListener('click',e=>{let d=e.target.closest('[data-dog]');if(d)return detail(d.dataset.dog);if(e.target.closest('[data-add]'))return editDog();let g=e.target.closest('[data-go]');if(g)return setView(g.dataset.go);if(e.target.closest('[data-route]'))return setView('route');if(e.target.closest('[data-back]'))return setView('home');if(e.target.closest('#open-route'))return openRoute()});
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#fab').onclick=()=>editDog();$('#save-dog').onclick=saveDog;$('#delete-dog').onclick=del;$('#add-walk-slot').onclick=()=>addSlot(walkSlots);$('#add-sit-slot').onclick=()=>addSlot(sitSlots);walkOn.onchange=()=>{walkEditor.hidden=!walkOn.checked;if(walkOn.checked&&!walkSlots.children.length)addSlot(walkSlots)};sitOn.onchange=()=>{sitEditor.hidden=!sitOn.checked;if(sitOn.checked&&!sitSlots.children.length)addSlot(sitSlots)};$('#photo-input').onchange=async e=>{try{photo(await shrink(e.target.files[0]))}catch{toast('Could not use that photo')}};$('#backup-button').onclick=()=>dataDlg.showModal();$('[data-close-dialog="data-dialog"]').onclick=()=>dataDlg.close();$('#export-data').onclick=backup;$('#import-data').onchange=e=>restore(e.target.files[0]);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));setView('home');
})();